#! /usr/bin/env python
#
# sma2-upload-to-pvoutputorg - Upload generation history to pvoutput.org
# Copyright (C) 2014 Peter Barker <pb-sma2@barker.dropbear.id.au>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

from __future__ import print_function

import sys

import smadata2.protocol
import smadata2.util
import smadata2.config
import smadata2.db

import smadata2.pvoutputorg
import smadata2.uploadinverterdatatopvoutputorg
import time
import datetime

config = smadata2.config.SMAData2Config()

db = smadata2.db.SMADatabaseSQLiteV0(config.dbname)

pvoutput_config_filepath = config.pvoutput_config_filepath

mypvoutput = smadata2.pvoutputorg.PVOutputOrg(pvoutput_config_filepath)

if True:
    for inv in config.inverters():
        print("%s (SN: %d)" % (inv.name, inv.serial))
        uploader = smadata2.uploadinverterdatatopvoutputorg.uploadInverterDataToPVOutputOrg(db, inv, mypvoutput)
        uploader.upload_unuploaded_statuses_batch()

sys.exit(0)

# stuff below this line is useful for fixing data on the server - and
# working out what needs fixing....

if False:
    for inv in config.inverters():
        print("%s (SN: %d)" % (inv.name, inv.serial))
        uploader = SMA2UploadInverterDataToPVOutputOrg(db, inv, mypvoutput)
        uploader.show_production_for_datapoint("20141029", "19:15")
        uploader.show_production_for_datapoint("20141029", "19:20")
        uploader.show_production_for_datapoint("20141029", "19:25")
        uploader.show_production_for_datapoint("20141029", "19:30")
        uploader.show_production_for_datapoint("20141030", "06:30")
        uploader.show_production_for_datapoint("20141030", "06:35")
        uploader.show_production_for_datapoint("20141030", "06:40")
    sys.exit(0)

if False:
    for inv in config.inverters():
        print("%s (SN: %d)" % (inv.name, inv.serial))
        uploader = SMA2UploadInverterDataToPVOutputOrg(db, inv, mypvoutput)
        somedate = mypvoutput.parse_date_and_time('20141031', '00:00')
        uploader.reconcile_date(somedate)
    sys.exit(0)

if False:
    for inv in config.inverters():
        print("%s (SN: %d)" % (inv.name, inv.serial))
        uploader = SMA2UploadInverterDataToPVOutputOrg(db, inv, mypvoutput)
        uploader.reconcile()
    sys.exit(0)

if False:
    date = "20141104"
    fix = True

    for inv in config.inverters():
        uploader = SMA2UploadInverterDataToPVOutputOrg(db, inv, mypvoutput)
        uploader.do_date(date, fix)
    sys.exit(0)
